
image:
  repository: furikuri/jenkins-lab
  tag: 2.140
  pullPolicy: IfNotPresent

service:
  httpPort: 80
  type: LoadBalancer

ingress:
  enabled: false

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  requests:
    memory: 512Mi
    cpu: 300m

helloWorld: hello